### ISSUE TITLE
define corpus name and corpus data + registry dir in input dict

### ISSUE THREAD

**Issue by iulusoy** [ssciwr/argumentation-management#36]

**Comment by np179** [comment]
Sollte mit [https://github.com/ssciwr/argumentation-management/pull/38/commits/f78a6fd21d5f7d6e5bf6993f87427fcf8f94e20d](url) erledigt sein. Habe die Parameter im Dict mal so gesetzt wie sie in der Funktion gegeben waren.

**Comment by np179** [comment]
Habe in https://github.com/ssciwr/argumentation-management/commit/be37ca07fc8846de4b861fd6c8c83cdf607092b9 die Pipelines so angepasst, dass sie mit dem geänderten Input funktionieren.
